# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  basicappcustomers:
    image: basicappcustomers
    build:
      context: .
      dockerfile: src/basicapp.api/BasicAppCustomers/BasicAppCustomers/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  basicappui:
    image: basicappui
    build:
      context: .
      dockerfile: src/basicapp.ui/Dockerfile
  proxy:
    image: nginx
    ports:
      - 443:443
      - 3000:443
      - 8080:443
      - 7293:443
      - 5293:443
      - 80:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  postgres:
    image: postgres
    volumes:
      - apidb:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 6lIclDmGQ82UlPLgrG0z9ynwT1ckZQISmpVxsoD6
      POSTGRES_DB: basicapp
      POSTGRES_USER: basicapp
volumes:
  apidb:
